####################################################################
# Example : LDEV  Playbook
####################################################################
- name: Logical Device Module
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:
    ####################################################################
    # Task 6 : Present ldevs to hostgroup
    ####################################################################
    - name: Present ldevs to hostgroup CL2-A
      hv_hg:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_present }}"
        spec:
          state: "present"
          name: "{{host_group_name}}"
          port: "CL2-A"
          ldevs: "{{ ldev_id }}"
      register: host_group_create

    - debug:
        var: host_group_create
