####################################################################
# Example : LDEV  Playbook
####################################################################
- name: Logical Device Module
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:

####################################################################
# Task 1 : Create shadow image pair
####################################################################
    - name: Create shadow image pair
      hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_sync }}"
        spec:
          primary_volume_id: "{{ snapshot_source_volume }}"
          secondary_volume_id: "{{ snapshot_destination_volume }}"
          copy_pace_track_size: "{{ shadow_image_pair_copy_pace_track_size_1 }}"
          enable_quick_mode: "{{ shadow_image_pair_enable_quick_mode_1 }}"
          auto_split: true
      register: result

    - debug:
        var: result
####################################################################
# Task 2 : Split shadow image pair
####################################################################
    - name: Split shadow image pair
      hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_split }}"
        spec:
          primary_volume_id: "{{ snapshot_source_volume }}"
          secondary_volume_id: "{{ snapshot_destination_volume }}"
          enable_quick_mode: "{{ shadow_image_pair_enable_quick_mode_2 }}"
          enable_read_write: "{{ shadow_image_pair_enable_read_write_2 }}"
      register: result

    - debug:
        var: result