---
####################################################################
# Example :  Global Active Device Pair (GAD) Playbook
####################################################################
- name: GAD - Global Active Device Pair Management
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"

  tasks:
    ####################################################################
    # Task 1 : Create GAD pair with single server configuration
    ####################################################################
    - name: Create GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        storage_system_info:
          serial: "{{ storage_serial }}"
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"

        spec:
          copy_group_name: "{{copy_group_name}}"
          copy_pair_name: "{{copy_pair_name}}"

          primary_storage_serial_number: "{{storage_serial}}"
          secondary_storage_serial_number: "{{secondary_storage_serial}}"
          primary_volume_id: "{{primary_volume_id}}"
          secondary_pool_id: "{{secondary_pool_id}}"
          secondary_hostgroups:
            - name: "{{host_group}}"
              port: "CL3-A"
              enable_preferred_path: false
          quorum_disk_id: "{{quorum_disk_id}}"

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 2 : Create GAD pair with  server cluster configuration
    ####################################################################
    - name: Create GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        storage_system_info:
          serial: "{{ storage_serial }}"
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"

        spec:
          copy_group_name: "{{copy_group_name}}"
          copy_pair_name: "{{copy_pair_name}}"
          primary_volume_id: "{{primary_volume_id}}"
          primary_storage_serial_number: "{{storage_serial}}"
          secondary_storage_serial_number: "{{secondary_storage_serial}}"
          secondary_pool_id: "{{ secondary_pool_id }}"
          secondary_hostgroups:
            - name: "{{host_group}}"
              port: "CL3-A"
              enable_preferred_path: false
          primary_hostgroups:
            - name: "{{host_group}}"
              port: "CL1-A"
              enable_preferred_path: false
          quorum_disk_id: "{{quorum_disk_id}}"
          allocate_new_consistency_group: false
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 3 : Create GAD pair with cross path server configuration
    ####################################################################
    - name: Create GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        storage_system_info:
          serial: "{{ storage_serial }}"
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"

        spec:
          copy_group_name: "{{copy_group_name}}"
          copy_pair_name: "{{copy_pair_name}}"

          primary_storage_serial_number: "{{storage_serial}}"
          secondary_storage_serial_number: "{{secondary_storage_serial}}"
          primary_volume_id: "{{primary_volume_id}}"
          secondary_pool_id: "{{secondary_pool_id}}"
          secondary_hostgroups:
            - name: "{{host_group}}"
              port: "CL3-A"
              enable_preferred_path: false
          primary_hostgroups:
            - name: "{{host_group}}"
              port: "CL1-A"
              enable_preferred_path: false
          primary_resource_group_name: "{{primary_resource_group_name}}"
          quorum_disk_id: "{{quorum_disk_id}}"
          set_alua_mode: false
          allocate_new_consistency_group: false
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 4 : Split GAD pair
    ####################################################################
    - name: Split GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        storage_system_info:
          serial: "{{ storage_serial }}"
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"

        state: "split"
        spec:
          copy_group_name: "{{copy_group_name}}"
          copy_pair_name: "{{copy_pair_name}}"
          local_device_group_name: "{{copy_group_name}}"
          remote_device_group_name: "{{copy_group_name}}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 5 : Resync GAD pair
    ####################################################################
    - name: Resync GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        storage_system_info:
          serial: "{{ storage_serial }}"
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"

        state: "resync"
        spec:
          copy_group_name: "{{copy_group_name}}"
          copy_pair_name: "{{copy_pair_name}}"
          local_device_group_name: "{{copy_group_name}}"
          remote_device_group_name: "{{copy_group_name}}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result



    #####################################################################
    # Task 9 : Resize GAD pair
    ######################################################################
    - name: Resize GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "resize"
        spec:
          copy_group_name: "{{copy_group_name}}"
          copy_pair_name: "{{copy_pair_name}}"
          new_volume_size: "10GB"

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 6 : Delete GAD pair
    ####################################################################
    - name: Delete GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        storage_system_info:
          serial: "{{ storage_serial }}"
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"

        state: "absent"
        spec:
          copy_group_name: "{{copy_group_name}}"
          primary_storage_serial_number: "{{storage_serial}}"
          secondary_storage_serial_number: "{{secondary_storage_serial}}"
          primary_volume_id: "{{primary_volume_id}}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
