---
####################################################################
# Example :  Global Active Device Pair (GAD) Playbook
####################################################################
- name: GAD - Global Active Device Pair Management
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"

  tasks:
    ####################################################################
    # Task 3 : Create GAD pair with cross path server configuration
    ####################################################################
    - name: Create GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        storage_system_info:
          serial: 810396
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
        spec:
          copy_group_name: "{{ldev_id}}_gad_migration_group"
          copy_pair_name: "{{ldev_id}}_gad_migration_pair"

          primary_volume_id: "{{ldev_id}}"
          secondary_pool_id: 1
          secondary_hostgroups:
            - name: "WilliamGAD"
              port: "CL1-A"
              enable_preferred_path: true
          primary_hostgroups:
            - name: "WilliamGAD"
              port: "CL1-A"
              enable_preferred_path: true
          primary_resource_group_name: "VSM_487953"
          primary_storage_serial_number: "{{primary_storage_serial}}"
          secondary_storage_serial_number: "{{secondary_storage_serial}}"
          secondary_resource_group_name: "VSM_487953"
          quorum_disk_id: 0
          set_alua_mode: true
          allocate_new_consistency_group: false
      register: result
      ignore_errors: True

    - name: Collect log bundle for direct only
      hitachivantara.vspone_block.vsp.hv_troubleshooting_facts:
      # no_log: true

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    - name: Get all GAD pairs  for direct connection type
      hitachivantara.vspone_block.vsp.hv_gad_facts:
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
      register: gad_facts
#      until: gad_facts.stdout.find("PAIR") != -1
#      retries: 60
#      delay: 10

    - name: Set paths on old array as non-preferred.
      hitachivantara.vspone_block.vsp.hv_hg:
        state: present
        connection_info: "{{ connection_info }}"
        spec:
          state: set_host_mode_and_hmo
          name: 'WilliamGAD'
          port: '{{item}}'
          host_mode_options: [ 78 ]
      loop:
        - "CL1-A"
        - "CL2-A"

    - name: Debug gad results
      ansible.builtin.debug:
        var: gad_facts

