---
# Playbook: monitor_hitachi_storage.yml
# Description: Collects storage pool usage information from Hitachi storage arrays
#              and stores results sorted by pool capacity.

- name: Monitor Hitachi Storage Arrays
  hosts: localhost
  gather_facts: no
  vars:
    hitachi_username: "{{ vault_storage_username }}"
    hitachi_password: "{{ vault_storage_secret }}"
    hitachi_storage_ips:
      - 192.168.180.12
      - 192.168.181.12
      - 192.168.180.163
    results_path: "./hitachi_pool_usage.json"
    temp_pool_results: []

  tasks:


    - name: Create temporary directory for results
      tempfile:
        state: directory
        suffix: hitachi
      register: temp_dir

    - name: Process each Hitachi storage array
      block:
        - name: Connect to Hitachi storage array and retrieve pool information
          uri:
            url: "https://{{ item }}/ConfigurationManager/v1/objects/pools"
            method: GET
            user: "{{ vault_storage_username }}"
            password: "{{ vault_storage_secret }}"
            force_basic_auth: yes
            validate_certs: no
            headers:
              Accept: "application/json"
              Content-Type: "application/json"
          register: pool_response
          with_items: "{{ hitachi_storage_ips }}"
          ignore_errors: yes
          no_log: yes

        - name: Print summary of pool usage
          debug:
            var: pool_response



        - name: Reset temp_pool_results
          set_fact:
            temp_pool_results: [ ]

        - name: Process pool data for array
          set_fact:
            temp_pool_results: "{{ temp_pool_results + [
              {
                'array_ip': array_response.item,
                'pool_id': pool.poolId,
                'pool_name': pool.poolName,
                'capacity_gb': ((pool.totalPoolCapacity | int) / 1024 / 1024),
                'used_capacity_gb': ((pool.totalPoolCapacity | int - pool.availableVolumeCapacity | int) / 1024 / 1024),
                'usage_percent': pool.usedCapacityRate | int,
                'status': pool.poolStatus,
                'warning_threshold': pool.warningThreshold | int,
                'depletion_threshold': pool.depletionThreshold | int,
                'pool_type': pool.poolType,
                'total_located_capacity_gb': ((pool.totalLocatedCapacity | default(0) | int) / 1024 / 1024)
              }
            ] }}"
          loop: "{{ array_response.json.data }}"
          loop_control:
            loop_var: pool
            label: "{{ array_response.item }} - {{ pool.poolName | default('unknown') }}"

        - name: Print Pool Information
          debug:
            var: temp_pool_results


        - name: Sort pools by capacity (descending)
          set_fact:
            sorted_pools: "{{ temp_pool_results | sort(attribute='capacity_gb', reverse=true) }}"


        - name: Print Sorted Pool Information
          debug:
            var: sorted_pools

        - name: Group pools by array
          set_fact:
            pools_by_array: "{{ pools_by_array | default({}) | combine({item.array_ip: (pools_by_array[item.array_ip] | default([]) + [item | dict2items | rejectattr('key', 'equalto', 'array_ip') | items2dict])}) }}"
          loop: "{{ temp_pool_results | default([]) }}"
          when: temp_pool_results is defined and flat_pool_results | length > 0

        - name: Print Group Pool Information
          debug:
            var: pools_by_array

        - name: Generate final report with usage percentages
          copy:
            content: "{{ pools_by_array | to_nice_json }}"
            dest: "{{ results_path }}"
          delegate_to: localhost

        - name: Print summary of pool usage
          debug:
            msg: |
              Hitachi Storage Array Pool Usage Summary:
              {% for array_ip, pools in pools_by_array.items() %}
              Storage Array: {{ array_ip }}
              {% for pool in pools %}
              - Pool: {{ pool.pool_name }} (ID: {{ pool.pool_id }})
                Capacity: {{ pool.capacity_gb | round(2) }} GB
                Used: {{ pool.used_capacity_gb | round(2) }} GB
                Usage: {{ pool.usage_percent }}%
                Status: {{ pool.status }}
              {% endfor %}
              {% endfor %}

      rescue:
        - name: Report error when processing storage arrays
          debug:
            msg: "Failed to collect information from one or more storage arrays. Please check credentials and connectivity."

      always:
        - name: Clean up temporary directory
          file:
            path: "{{ temp_dir.path }}"
            state: absent
          when: temp_dir.path is defined

    - name: Alert on high pool usage
      debug:
        msg: "WARNING: Pool {{ item.pool_name }} on array {{ item.array_ip }} has {{ item.usage_percent }}% usage, which exceeds threshold!"
      loop: "{{ sorted_pools }}"
      when: item.usage_percent | float > 85
