---
####################################################################
# Example :  Global Active Device Pair (GAD) Playbook
####################################################################
- name: GAD - Global Active Device Pair Expand
  hosts: localhost
  gather_facts: false
  vars_files:

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    volume_size: 10
    ticket: "srv109045"

  tasks:
    ####################################################################
    # Task Name : Create GAD pair with cross path server configuration
    ####################################################################
    - name: Increase size of volumes of a GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        state: "resize"
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
        spec:
          copy_group_name: "{{ticket}}_copy_group"
          copy_pair_name: "{{ticket}}_copy_pair"
          new_volume_size: "{{volume_size}}GB"
