---
# Playbook: monitor_hitachi_storage.yml
# Description: Collects storage pool usage information from Hitachi storage arrays
#              and stores results sorted by pool capacity.

- name: Consider Performance
  hosts: localhost
  gather_facts: no
  vars:
    hitachi_username: "{{ vault_storage_username }}"
    hitachi_password: "{{ vault_storage_secret }}"
    hitachi_storage_ips:
      - 192.168.180.12
      - 192.168.181.12
      - 192.168.180.163


  tasks:
    - name: Sleep for 300 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: "{{ 10 | random}}"
      delegate_to: localhost