---
####################################################################
# Example : Shadow Image Pair Playbook
####################################################################
- name: Shadow Image Pair Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task 1 : Create shadow image pair
    ####################################################################
    - name: Create shadow image pair
      hitachivantara.vspone_block.vsp.hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "present"
        spec:
          primary_volume_id: 274
          secondary_volume_id: 277
          allocate_new_consistency_group: true
          copy_pace_track_size: "MEDIUM"
          enable_quick_mode: false
          auto_split: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 2 : Split shadow image pair
    ####################################################################
    - name: Split shadow image pair
      hitachivantara.vspone_block.vsp.hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "split"
        spec:
          primary_volume_id: 274
          secondary_volume_id: 277
          enable_quick_mode: true
          enable_read_write: false
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 3 : Resync shadow image pair
    ####################################################################
    - name: Resync shadow image pair
      hitachivantara.vspone_block.vsp.hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "sync"
        spec:
          primary_volume_id: 274
          secondary_volume_id: 277
          enable_quick_mode: false
          copy_pace_track_size: "MEDIUM"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 4 : Create and Auto-Split shadow image pair
    ####################################################################
    - name: Create and Auto-Split shadow image pair
      hitachivantara.vspone_block.vsp.hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "split"
        spec:
          primary_volume_id: 274
          secondary_volume_id: 277
          allocate_new_consistency_group: true
          consistency_group_id: 1
          copy_pace_track_size: "MEDIUM"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 5 : Restore shadow image pair
    ####################################################################
    - name: Restore shadow image pair
      hitachivantara.vspone_block.vsp.hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "restore"
        spec:
          primary_volume_id: 274
          secondary_volume_id: 277
          enable_quick_mode: true
          copy_pace_track_size: "MEDIUM"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 6 : Delete shadow image pair
    ####################################################################
    - name: Delete shadow image pair
      hitachivantara.vspone_block.vsp.hv_shadow_image_pair:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "absent"
        spec:
          primary_volume_id: 274
          secondary_volume_id: 277
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
