####################################################################
# Example : Shadow Image Pair Facts Playbook
####################################################################
- name: Shadow Image Pair Facts
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
####################################################################
# Task 1 : Get all shadow image pairs
####################################################################
    - name: Get all shadow image pairs
      hv_shadow_image_pair_facts:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
      register: result

    - debug:
        var: result

####################################################################
# Task 2 : Get shadow image pairs by primary_volume_id
####################################################################
    - name: Get shadow image pairs by primary_volume_id
      hv_shadow_image_pair_facts:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          primary_volume_id: "{{ shadow_image_pair_facts_pvol_2 }}"
      register: result

    - debug:
        var: result
