---
####################################################################
# Example : Snapshot group Pair Facts playbook
####################################################################

- name: Snapshot group Pair Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task 1 : Get all snapshot pairs using group name
    ####################################################################
    - name: Get one snapshot pairs using group name
      hitachivantara.vspone_block.vsp.hv_snapshot_group_facts:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          snapshot_group_name: "snapshot-group-name-1"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
