####################################################################
# Example :  Storage Port Facts Playbook
####################################################################
- name: Storage Port Facts
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
####################################################################
# Task 1 : Get all storage ports
####################################################################
    - name: Get all storage ports
      hv_storage_port_facts:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
      register: result

    - debug:
        var: result

####################################################################
# Task 2 : Get storage port details using port ids
####################################################################
    - name: Get storage port details using port ids
      hv_storage_port_facts:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          ports: "{{ storage_port_facts_ports_2 }}"
      register: result

    - debug:
        var: result
