namespace: hitachivantara
name: vspone_block
version: 3.0.128
readme: README.md
authors:
  - Hitachi Vantara Ansible Team 
description: Ansible Modules to manage Hitachi Storage and Data Services (Block, File etc.)
  using the Hitachi VSP One platform. These modules provide a simplified and
  automated way to configure and manage Hitachi storage systems, enabling
  seamless integration with Ansible playbooks and workflows.
license:
  - GPL-3.0-or-later
tags:
  - hitachi
  - hv
  - hitachi_vantara
  - sds_block
  - vsp
  - vsp_one
  - storage
  - pegasus
dependencies: {}
repository: https://github.com/hitachi-vantara/vspone-block-ansible
documentation: https://github.com/hitachi-vantara/vspone-block-ansible
issues: https://github.com/hitachi-vantara/vspone-block-ansible/issues
build_ignore:
  - tests/integration/  # Example: Ignore integration tests
  - .git
  - collection_build.sh
  - .pylintrc
  - .gitignore
  - Dockerfile
  - pylint_run_report.txt
