####################################################################
# Example : Chap User Playbook
####################################################################
- name: Chap User
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.sds_block

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - sds_block_variables.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  
  tasks:
####################################################################
# Task 1 : Create chap user
####################################################################
    - name: Create chap user
      hv_sds_block_chap_user:
        connection_info: "{{ connection_info }}"
        state: "{{ state_present }}"
        spec:
          target_chap_user_name: "{{ chap_user_target_chap_user_name_1 }}"
          target_chap_secret: "{{ chap_user_target_chap_secret_1 }}"
          initiator_chap_user_name: "{{ chap_user_initiator_chap_user_name_1 }}"
          initiator_chap_secret: "{{ chap_user_initiator_chap_secret_1 }}"
      register: result

    - debug:
        var: result

####################################################################
# Task 2 : Update chap user name
####################################################################
    - name: Update chap user name
      hv_sds_block_chap_user:
        connection_info: "{{ connection_info }}"
        state: "{{ state_present }}"
        spec:
          id: "{{ chap_user_id_2 }}"
          target_chap_user_name: "{{ chap_user_target_chap_user_name_2}}"
      register: result

    - debug:
        var: result

####################################################################
# Task 3 : Update chap user name and secret
####################################################################
    - name: Update chap user secret
      hv_sds_block_chap_user:
        connection_info: "{{ connection_info }}"
        state: "{{ state_present }}"
        spec:
          id: "{{ chap_user_id_3 }}"
          target_chap_user_name: "{{ chap_user_target_chap_user_name_3}}"
          target_chap_secret: "{{ chap_user_target_chap_secret_3 }}"
      register: result

    - debug:
        var: result

####################################################################
# Task 4 : Delete chap user
####################################################################
    - name: Delete chap user
      hv_sds_block_chap_user:
        connection_info: "{{ connection_info }}"
        state: "{{ state_absent }}"
        spec:
          id: "{{ chap_user_id_4 }}"
      register: result

    - debug:
        var: result
