####################################################################
# Example : StorageSystem Facts Playbook
####################################################################
- name: StorageSystem Facts
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.sds_block

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  
  tasks:
####################################################################
# Task 1 : Get storage system facts
####################################################################
    - name: Get storage system facts
      hv_sds_block_storage_system_fact:
        connection_info: "{{ connection_info }}"
      register: result

    - debug:
        var: result
