####################################################################
# Example : Update UAI Gateway admin user password playbook
####################################################################
- name: Admin Password
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml

  tasks:
####################################################################
# Task 0 : Get UAI gateway token
####################################################################
      - name: Get UAI gateway token
        hv_uaig_token_fact:
          connection_info:
            address: "{{ uai_gateway_address }}"
            username: "{{ vault_gateway_username }}"
            password: "{{ vault_gateway_secret }}"
        register: result_token
        ignore_errors: False

#######################################################################
# Task 1 : Update UAI Gateway admin user password
#######################################################################
      - name: Update UAI Gateway admin user password
        hv_gateway_admin_password:
          connection_info:
            uai_gateway_address: "{{ uai_gateway_address }}"
            api_token: "{{ result_token.api_token.token }}"
          spec:
            password: "{{ admin_password_password_1 }}"
        register: result

      - debug:
        var: result

   
