---
####################################################################
# Example :  Global-active device (GAD) Pair  playbook
####################################################################
- name: GAD - Global Active Device Pair
  hosts: localhost

  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  tasks:
    ####################################################################
    # Task 0 : Get UAI gateway token
    ####################################################################
    - name: Get UAI gateway token
      hitachivantara.vspone_block.vsp.hv_uaig_token_facts:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: false

    #####################################################################
    # Task 1 : Create GAD pair with single server configuration
    #####################################################################
    - name: Create GAD pair with single server configuration
      hitachivantara.vspone_block.vsp.hv_gad:
        storage_system_info:
          serial: "{{ storage_serial }}"
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        spec:
          primary_storage_serial_number: "{{ storage_serial }}"
          secondary_storage_serial_number: "{{ secondary_storage_serial }}"
          primary_volume_id: 123
          secondary_pool_id: 3
          secondary_hostgroup:
            name: remote-hostgroup
            port: CL1-A
          primary_resource_group_name: primary_resource_group
          quorum_disk_id: 10
          allocate_new_consistency_group: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 2 : Create GAD pair with  server cluster configuration
    #####################################################################
    - name: Create GAD pair with  server cluster configuration
      hitachivantara.vspone_block.vsp.hv_gad:
        storage_system_info:
          serial: "{{ storage_serial }}"
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        spec:
          primary_storage_serial_number: "{{ storage_serial }}"
          secondary_storage_serial_number: "{{ secondary_storage_serial }}"
          primary_volume_id: 123
          secondary_pool_id: 3
          primary_hostgroups:
            name: local-hostgroup
            port: CL2-A
          secondary_hostgroup:
            name: remote-hostgroup
            port: CL1-A
          quorum_disk_id: 10
          allocate_new_consistency_group: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 3 : Create GAD pair with cross path server configuration
    #####################################################################
    - name: Create GAD pair with cross path server configuration
      hitachivantara.vspone_block.vsp.hv_gad:
        storage_system_info:
          serial: "{{ storage_serial }}"
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        spec:
          primary_storage_serial_number: "{{ storage_serial }}"
          secondary_storage_serial_number: "{{ secondary_storage_serial }}"
          primary_volume_id: 123
          secondary_pool_id: 3
          primary_hostgroups:
            name: local-hostgroup
            port: CL2-A
          secondary_hostgroup:
            name: remote-hostgroup
            port: CL1-A
          quorum_disk_id: 10
          set_alua_mode: true
          allocate_new_consistency_group: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 4 : Split GAD pair
    #####################################################################
    - name: Split GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: split
        spec:
          primary_volume_id: 123
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 5 : Resync GAD pair
    #####################################################################
    - name: Resync GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: resync
        spec:
          primary_volume_id: 123
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 6 : Delete GAD pair
    #####################################################################
    - name: Delete GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: absent
        spec:
          primary_volume_id: 123
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 7 : Resize GAD pair
    ######################################################################
    - name: Resize GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: resize
        spec:
          primary_volume_id: 123
          new_volume_size: 4000
          secondary_storage_serial_number: "{{ secondary_storage_serial }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
