####################################################################
# Example :  Global-active device (GAD) Pair Facts playbook
####################################################################
- name: GAD pair facts
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_uai_gateway_variables.yml

  tasks:
####################################################################
# Task 0 : Get UAI gateway token
####################################################################
    - name: Get UAI gateway token
      hv_uaig_token_fact:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: False

#####################################################################
# Task 1 : Get all GAD pairs
######################################################################
    - name: Get all GAD pairs
      hv_gad_fact:
        connection_info:
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          connection_type: "{{ connection_type }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
      register: result

    - debug:
        var: result

######################################################################
# Task 2 : Get GAD pair using primary volume id
######################################################################
    - name: Get GAD pair using primary volume id
      hv_gad_fact:
        connection_info:
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          connection_type: "{{ connection_type }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          primary_volume_id: "{{ gad_pair_facts_primary_volume_id_2 }}"
      register: result

    - debug:
        var: result
