####################################################################
# Example : Hostgroup Facts playbook
####################################################################
- name: Hostgroup Facts
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_uai_gateway_variables.yml

  tasks:
####################################################################
# Task 0 : Get UAI gateway token
####################################################################
    - name: Get UAI gateway token
      hv_uaig_token_fact:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: False

#####################################################################
# Task 1 : Get all hostgroups
#####################################################################   
    - name: Get all hostgroups
      hv_hg_facts:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          subscriber_id: "{{ subscriber_id }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
      register: result

    - debug:
        var: result

#####################################################################
# Task 2 : Get hostgroups of specific ports
#####################################################################
    - name: Get hostgroups of specific ports
      hv_hg_facts:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          subscriber_id: "{{ subscriber_id }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          ports: "{{ hostgroup_facts_ports_2 }}"
      register: result

    - debug:
        var: result

#####################################################################
# Task 3 : Get hostgroups of specific ports with same hg name
######################################################################
    - name: Get hostgroups of specific ports with same hg name
      hv_hg_facts:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          subscriber_id: "{{ subscriber_id }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          ports: "{{ hostgroup_facts_ports_3 }}"
          name: "{{ hostgroup_facts_name_3 }}"
      register: result

    - debug:
        var: result

#####################################################################
# Task 4 : Get hostgroups of specific ports, include wwns and ldevs
######################################################################
    - name: Get hostgroups of specific ports, include wwns and ldevs
      hv_hg_facts:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          subscriber_id: "{{ subscriber_id }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          ports: "{{ hostgroup_facts_ports_4 }}"
          query: "{{ hostgroup_facts_query_4 }}"
      register: result

    - debug:
        var: result

