---
####################################################################
# Example :  Hitachi Universal Replicator (HUR) playbook
####################################################################
- name: HUR - Hitachi Universal Replicator Pair
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  tasks:
    ####################################################################
    # Task 0 : Get UAI gateway token
    ####################################################################
    - name: Get UAI gateway token
      hitachivantara.vspone_block.vsp.hv_uaig_token_facts:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: false

    #####################################################################
    # Task 1 : Create HUR pair
    ######################################################################
    - name: Create HUR pair
      hitachivantara.vspone_block.vsp.hv_hur:
        storage_system_info:
          serial: "{{ storage_serial }}"
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        spec:
          primary_volume_id: 123
          primary_volume_journal_id: 1
          secondary_volume_journal_id: 2
          secondary_pool_id: 3
          allocate_new_consistency_group: true
          secondary_storage_serial_number: 23456
          secondary_hostgroup:
            name: remote-hostgroup-1
            port: CL1-A
          mirror_unit_id: 1
          begin_secondary_volume_id: 123
          end_secondary_volume_id: 256
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 2 : Split HUR pair
    ######################################################################
    - name: Split HUR pair
      hitachivantara.vspone_block.vsp.hv_hur:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: split
        spec:
          primary_volume_id: 123
          mirror_unit_id: 1
          is_svol_readwriteable: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 3 : Resync HUR pair
    ######################################################################
    - name: Resync HUR pair
      hitachivantara.vspone_block.vsp.hv_hur:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: resync
        spec:
          primary_volume_id: 123
          mirror_unit_id: 1
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 4 : Delete HUR pair
    ######################################################################
    - name: Delete HUR pair
      hitachivantara.vspone_block.vsp.hv_hur:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: absent
        spec:
          primary_volume_id: 123
          mirror_unit_id: 1
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ######################################################################
    # Task 5 : Swap-Split HUR pair
    ######################################################################
    - name: Swap-Split HUR pair
      hitachivantara.vspone_block.vsp.hv_hur:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: 23456
        state: swap_split
        spec:
          primary_volume_id: 123
          mirror_unit_id: 1
          secondary_storage_serial_number: "{{ storage_serial }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 6 : Swap-Resync HUR pair
    ######################################################################
    - name: Swap-Resync HUR pair
      hitachivantara.vspone_block.vsp.hv_hur:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: 23456
        state: swap_resync
        spec:
          primary_volume_id: 123
          mirror_unit_id: 1
          secondary_storage_serial_number: "{{ storage_serial }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 7 : Resize HUR pair
    ######################################################################
    - name: Resize HUR pair
      hitachivantara.vspone_block.vsp.hv_hur:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: resize
        spec:
          primary_volume_id: 123
          new_volume_size: 4000
          secondary_storage_serial_number: 23456
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
