####################################################################
# Example : Provision ldev to host Playbook
####################################################################
- name: Provision ldev to host
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_uai_gateway_variables.yml

  tasks:
####################################################################
# Task 0 : Get UAI gateway token
####################################################################
    - name: Get UAI gateway token
      hv_uaig_token_fact:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: False

####################################################################
# Task 1 : Create ldev with gateway connection
####################################################################
    - name: Create ldev with gateway connection
      hv_ldev:
        storage_system_info:
          serial: '{{ storage_serial }}'   
        connection_info:
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          subscriber_id: '{{ subscriber_id | default(omit) }}'
          connection_type: "{{ connection_type }}"
        state: "{{ state_present }}"
        spec:
          pool_id: "{{ provision_ldev_to_host_pool_id_1 }}"
          size: "{{ provision_ldev_to_host_size_1 }}"
          name: "{{ provision_ldev_to_host_name_1 }}"
      register: result_create_ldev

    - debug: 
        var: result_create_ldev

####################################################################
# Task 2 : Present ldev to host group with gateway connection
####################################################################
    - name: Present ldev to hostgroup with gateway connection

      hv_hg:

        storage_system_info:
          serial: '{{ storage_serial }}'
          
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          subscriber_id: '{{ subscriber_id | default(omit) }}'

        state: "{{ state_present }}"
        spec:
          state: "{{ substate_present_ldev }}"
          name: "{{ provision_ldev_to_host_name_2 }}"
          port: provision_ldev_to_host_port_2
          ldevs: ["{{ result_create_ldev['data']['ldev_id']  | int }}"]

      register: result_present_ldev

    - debug: 
        var: result_create_ldev
