---
####################################################################
# Example :  Storagesystem  Playbook
####################################################################
- name: StorageSystem Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  tasks:
    ####################################################################
    # Task 0 : Get UAI gateway token
    ####################################################################
    - name: Get UAI gateway token
      hitachivantara.vspone_block.vsp.hv_uaig_token_facts:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: false

    ####################################################################
    # Task 1 : Add storage system
    ####################################################################
    - name: Add storage system
      hitachivantara.vspone_block.vsp.hv_storagesystem:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
          address: "{{ storage_address }}"
          username: "{{ vault_storage_username }}"
          password: "{{ vault_storage_secret }}"
        state: present
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 2 : Add storage system with remote gateway address
    ####################################################################
    - name: Add storage system with remote gateway address
      hitachivantara.vspone_block.vsp.hv_storagesystem:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
          address: "{{ storage_address }}"
          username: "{{ vault_storage_username }}"
          password: "{{ vault_storage_secret }}"
          remote_gateway_address: 10.10.10.10
        state: present
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 3 : Delete storage system
    ####################################################################
    - name: Delete storage system
      hitachivantara.vspone_block.vsp.hv_storagesystem:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: absent
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
