---
####################################################################
# Example :  Storagesystem Facts Playbook
####################################################################
- name: StorageSystem Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  tasks:
    ####################################################################
    # Task 0 : Get UAI gateway token
    ####################################################################
    - name: Get UAI gateway token
      hitachivantara.vspone_block.vsp.hv_uaig_token_facts:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: false

    ####################################################################
    # Task 1 : Get storage system facts
    ####################################################################
    - name: Get storage system facts
      hitachivantara.vspone_block.vsp.hv_storagesystem_facts:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          refresh: false
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 2 : Get storage system facts using query
    ####################################################################
    - name: Get storage system facts using query
      hitachivantara.vspone_block.vsp.hv_storagesystem_facts:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          query:
            - ports
            - quorumdisks
            - journalPools
            - freeLogicalUnitList
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
