####################################################################
# Example :  Subscriber Playbook
####################################################################
- name: Subscriber Module
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - vsp_uai_gateway_variables.yml

  tasks:
####################################################################
# Task 0 : Get UAI gateway token
####################################################################
    - name: Get UAI gateway token
      hv_uaig_token_fact:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: False

####################################################################
# Task 1 : Create subscriber
####################################################################      
    - name: Create subscriber
      hv_gateway_subscriber:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        state: "{{ state_present }}"
        spec:
          subscriber_id: "{{ subscriber_subscriber_id_1 }}"
          name: "{{ subscriber_name_1 }}"
          soft_limit: "{{ subscriber_soft_limit_1 }}"
          hard_limit: "{{ subscriber_hard_limit_1 }}"
          quota_limit: "{{ subscriber_quota_limit_1 }}"
      register: result

    - debug:
        var: result

####################################################################
# Task 2 : Update subscriber
####################################################################
    - name: Update subscriber
      hv_gateway_subscriber:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        state: "{{ state_present }}"
        spec:
          subscriber_id: "{{ subscriber_subscriber_id_2 }}"
          name: "{{ subscriber_name_2 }}"
          soft_limit: "{{ subscriber_soft_limit_2 }}"
          hard_limit: "{{ subscriber_hard_limit_2 }}"
          quota_limit: "{{ subscriber_quota_limit_2 }}"
      register: result

    - debug:
        var: result

####################################################################
# Task 3 : Delete subscriber
####################################################################
    - name: Delete subscriber
      hv_gateway_subscriber:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        state: "{{ state_absent }}"
        spec:
          subscriber_id: "{{ subscriber_subscriber_id_3 }}"
      register: result

    - debug:
        var: result
