####################################################################
# Example :  TrueCopy Playbook
####################################################################
- name: TrueCopy Module
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_uai_gateway_variables.yml

  tasks:
####################################################################
# Task 0 : Get UAI gateway token
####################################################################
    - name: Get UAI gateway token
      hv_uaig_token_fact:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: False

####################################################################
# Task 1 : Create TrueCopy
####################################################################
    - name: Create TrueCopy
      hv_truecopy:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          subscriber_id: "{{ subscriber_id }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_present }}"
        spec:
          primary_volume_id: "{{ truecopy_primary_volume_id_1 }}"
          consistency_group_id: "{{ truecopy_consistency_group_id_1 }}"
          fence_level: "{{ truecopy_fence_level_1 }}"
          allocate_new_consistency_group: "{{ truecopy_allocate_new_consistency_group_1 }}"
          secondary_storage_serial_number: "{{ truecopy_secondary_storage_serial_number_1 }}"
          secondary_pool_id: "{{ truecopy_secondary_pool_id_1 }}"
          secondary_hostgroup:  "{{ truecopy_secondary_hostgroup_1 }}"
      register: result

    - debug:
        var: result

####################################################################
# Task 2 : Resync TrueCopy
####################################################################
    - name: Resync TrueCopy
      hv_truecopy:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_sync }}"
        spec:
          primary_volume_id: "{{ truecopy_primary_volume_id_2 }}"
      register: result

    - debug:
        var: result

####################################################################
# Task 3 : Split TrueCopy
####################################################################
    - name: Split TrueCopy
      hv_truecopy:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_split }}"
        spec:
          primary_volume_id: "{{ truecopy_primary_volume_id_3 }}"
      register: result

    - debug:
        var: result

####################################################################
# Task 4 : Delete TrueCopy
####################################################################
    - name: Delete TrueCopy
      hv_truecopy:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          subscriber_id: "{{ subscriber_id }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_absent }}"
        spec:
          primary_volume_id: "{{ truecopy_primary_volume_id_4 }}"
      register: result

    - debug:
        var: result