---
####################################################################
# Example :  TrueCopy Playbook
####################################################################
- name: TrueCopy Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  tasks:
    ####################################################################
    # Task 0 : Get UAI gateway token
    ####################################################################
    - name: Get UAI gateway token
      hitachivantara.vspone_block.vsp.hv_uaig_token_facts:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: false

    ####################################################################
    # Task 1 : Create TrueCopy
    ####################################################################
    - name: Create TrueCopy
      hitachivantara.vspone_block.vsp.hv_truecopy:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: present
        spec:
          primary_volume_id: 3555
          consistency_group_id: -1
          fence_level: NEVER
          allocate_new_consistency_group: false
          secondary_storage_serial_number: 800011
          secondary_pool_id: 4
          secondary_hostgroup:
            name: remote-hostgroup-1
            port: CL1-A
          begin_secondary_volume_id: 124
          end_secondary_volume_id: 129
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 2 : Resync TrueCopy
    ####################################################################
    - name: Resync TrueCopy
      hitachivantara.vspone_block.vsp.hv_truecopy:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: resync
        spec:
          primary_volume_id: 3555
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 3 : Split TrueCopy
    ####################################################################
    - name: Split TrueCopy
      hitachivantara.vspone_block.vsp.hv_truecopy:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: split
        spec:
          primary_volume_id: 3555
          is_svol_readwriteable: true
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 4 : Delete TrueCopy
    ####################################################################
    - name: Delete TrueCopy
      hitachivantara.vspone_block.vsp.hv_truecopy:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: absent
        spec:
          primary_volume_id: 3555
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #####################################################################
    # Task 5 : Resize TrueCopy pair
    ######################################################################
    - name: Resize TrueCopy pair
      hitachivantara.vspone_block.vsp.hv_truecopy:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: resize
        spec:
          primary_volume_id: 3555
          new_volume_size: 10GB
          secondary_storage_serial_number: 810045

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
