---
####################################################################
# Example :  Unsubscribe Resource Playbook
####################################################################
- name: Unsubscribe Resources
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  tasks:
    ####################################################################
    # Task 0 : Get UAI gateway token
    ####################################################################
    - name: Get UAI gateway token
      hitachivantara.vspone_block.vsp.hv_uaig_token_facts:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: false

    ####################################################################
    # Task 1 : Unsubscribe resources for the specific subscriber
    ####################################################################
    - name: Unsubscribe resources for the specific subscriber
      hitachivantara.vspone_block.vsp.hv_gateway_unsubscribe_resource:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          subscriber_id: "{{ subscriber_id }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          resources:
            - type: hostgroup
              values:
                - CL3-C, test-001
                - CLA-1, test-005
            - type: volume
              values: [5015, 5016]
            - type: port
              values: [CL5-A, CL1-A]
            - type: iscsitarget
              values:
                - CL4-C, iscsi-AnsibleAuto349605
                - CL4-C, Ansible-CreateISCSI-62117
            - type: storagepool
              values: [1HDP8]

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
