####################################################################
# Example :  Unsubscribe Resource Playbook
####################################################################
- name: Unsubscribe Resources
  hosts: localhost
  collections:
    - hitachivantara.vspone_block.vsp
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_gateway_var.yml
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_uai_gateway_variables.yml
  
  tasks:
####################################################################
# Task 0 : Get UAI gateway token
####################################################################
    - name: Get UAI gateway token
      hv_uaig_token_fact:
        connection_info:
          address: "{{ uai_gateway_address }}"
          username: "{{ vault_gateway_username }}"
          password: "{{ vault_gateway_secret }}"
      register: result_token
      ignore_errors: False

####################################################################
# Task 1 : Unsubscribe resources for the specific subscriber
####################################################################
    - name: Unsubscribe resources for the specific subscriber
      hv_gateway_unsubscribe_resource:
        connection_info:
          connection_type: "{{ connection_type }}"
          address: "{{ uai_gateway_address }}"
          api_token: "{{ result_token.api_token.token }}"
          subscriber_id: 12345
        storage_system_info:
          serial: "{{ storage_serial }}"
        spec:
          resources: "{{ unsubscribe_resource_resources_1 }}"

      register: result

    - debug:
        var: result