name: Publish Ansible Collection

on:
  push:
    tags:
      - "*"  # Triggers only when a version tag is pushed

jobs:
  verify_tests:
    name: Verify Test Results
    runs-on: ubuntu-latest

    steps:
      - name: Check Last Workflow Status
        id: check-tests
        uses: octokit/request-action@v4.x
        with:
          route: GET /repos/{owner}/{repo}/actions/runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse Test Results
        run: |
          latest_status=$(echo '${{ steps.check-tests.outputs.data }}' | jq -r '.workflow_runs[0].conclusion')
          echo "Latest test run status: $latest_status"
          if [[ "$latest_status" != "success" ]]; then
            echo "❌ Tests failed or not completed. Skipping publish."
            exit 1
          fi

  publish:
    name: Publish Collection
    needs: verify_tests  # Ensures publish only runs if tests passed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible Galaxy
        run: pip install ansible

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: collection-tarball

      - name: Extract Collection Name
        id: extract-name
        run: echo "COLLECTION_TAR=$(ls *.tar.gz)" >> $GITHUB_ENV

      - name: Publish to Ansible Galaxy
        run: ansible-galaxy collection publish $COLLECTION_TAR --api-key ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
